services:
  web:
    restart: always
    build:
      context: ./web
      dockerfile: ./.nixpacks/Dockerfile
      args:
        CI: "true"
        NIXPACKS_METADATA: "node"
        NODE_ENV: "production"
        NPM_CONFIG_PRODUCTION: "false"
    ports:
      - "1357:5173"
    volumes:
      - ./web:/app
    networks:
      critino_net:
        ipv4_address: 172.16.238.12
    env_file: ./web/.env

  api:
    restart: always
    build:
      context: ./services/api
      dockerfile: ./Dockerfile
    ports:
      - "7531:7531"
    volumes:
      - ./services/api:/app
    networks:
      critino_net:
        ipv4_address: 172.16.238.11
    env_file: ./services/api/.env
    command: poetry run fastapi dev src --host 0.0.0.0 --port 7531 --reload

networks:
  critino_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
